apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
  labels:
    name: myapp
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
      - containerPort: 80
  - name: sidecar
    image: busybox
    command: ["sh", "-c", "while true; do 'I love khgcode'; sleep 5; done"]